language: c
sudo: false
addons:
  apt:
    packages:
    - ocaml-nox
    - ocaml-findlib
    - dssi-dev

before_install:
  - git clone https://github.com/savonet/ocaml-ladspa.git
  - cd ocaml-ladspa && git submodule init && git submodule update && ./bootstrap && ./configure && make && cd ..

script:
  - ./bootstrap
  - ./configure --with-ladspa-dir=ocaml-ladspa/src
  - make
  - make -C examples
