name: CI

on: [push]

jobs:
  cancel_previous_run:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.4.0
        with:
          access_token: ${{ github.token }}

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install some plugins
      run: |
        sudo apt-get update
        sudo apt-get -y install dpf-plugins-dssi
    - name: Build and test module
      uses: savonet/build-and-test-ocaml-module@main

